[package]
name = "mounter"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "4.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
tabled = "0.15.0"
dialoguer = "0.11.0"
